## Muhammad Fikri
## 2109106010
## Informatika A 21
## Postest 7 KB

# Pengenalan Tensorflow

## LIBRARY

In [1]:
import tensorflow as tf

## 1. Buatlah sebuah tensor dengan shape(5,5) dengan nilai random yang disimpan dalam variable random_tensor.

In [2]:
random_tensor = tf.random.normal([5,5])
random_tensor.numpy()

array([[-0.27670863,  1.044424  ,  0.550125  , -0.99282146, -0.2260093 ],
       [ 0.962488  ,  0.6275071 ,  1.2158355 ,  2.606744  , -0.23018064],
       [ 1.7922432 , -2.2625775 , -0.6700773 ,  0.83154875,  0.19393615],
       [-0.23747538, -0.5474935 ,  0.15425   , -0.4497052 ,  1.3929794 ],
       [ 0.18530105,  1.2036611 ,  0.31885868, -0.95406336,  0.31005445]],
      dtype=float32)

## 2. Buatlah sebuah tensor dengan shape(5,5) dari sebuah list dengan nilai bilangan prima dalam variable prime_tensor.

In [3]:
prime_tensor = tf.convert_to_tensor([[1 , 3, 5, 7, 11],
                                    [13, 17, 19, 23, 29], 
                                    [31, 37, 41, 43, 47], 
                                    [53, 59, 61, 67, 71], 
                                    [73, 79, 83, 89, 97]], dtype=tf.float32)
print(prime_tensor)

tf.Tensor(
[[ 1.  3.  5.  7. 11.]
 [13. 17. 19. 23. 29.]
 [31. 37. 41. 43. 47.]
 [53. 59. 61. 67. 71.]
 [73. 79. 83. 89. 97.]], shape=(5, 5), dtype=float32)


## 3. Tampilkan dimensi dari kedua variable tersebut.

In [4]:
print("Dimensi Variabel")
print("Random_Tensor Dimensi :",random_tensor.shape)
print("Prime_Tensor Dimensi :",prime_tensor.shape) #dari bilangan prima

Dimensi Variabel
Random_Tensor Dimensi : (5, 5)
Prime_Tensor Dimensi : (5, 5)


## 4. Tampilkan hasil dari perhitungan aritmetika 2 variable tersebut (Gunakan minimal 5 operator).

### PENJUMLAHAN

In [5]:
x = random_tensor
y = prime_tensor
tf.add(x,y)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ 0.7232914,  4.044424 ,  5.550125 ,  6.0071783, 10.773991 ],
       [13.962488 , 17.627506 , 20.215836 , 25.606745 , 28.76982  ],
       [32.792244 , 34.737423 , 40.32992  , 43.83155  , 47.193935 ],
       [52.762524 , 58.452507 , 61.15425  , 66.55029  , 72.39298  ],
       [73.1853   , 80.20366  , 83.318855 , 88.04594  , 97.31005  ]],
      dtype=float32)>

### PERKALIAN

In [6]:
tf.multiply(x,y)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ -0.27670863,   3.1332722 ,   2.7506251 ,  -6.94975   ,
         -2.4861023 ],
       [ 12.512344  ,  10.667621  ,  23.100874  ,  59.955112  ,
         -6.6752386 ],
       [ 55.55954   , -83.71537   , -27.473171  ,  35.756596  ,
          9.114999  ],
       [-12.586195  , -32.302116  ,   9.409249  , -30.130249  ,
         98.901535  ],
       [ 13.526977  ,  95.089226  ,  26.465271  , -84.91164   ,
         30.075281  ]], dtype=float32)>

### PENGURANGAN

In [7]:
tf.subtract(x,y)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[ -1.2767086,  -1.955576 ,  -4.449875 ,  -7.9928217, -11.226009 ],
       [-12.037512 , -16.372494 , -17.784164 , -20.393255 , -29.23018  ],
       [-29.207756 , -39.262577 , -41.67008  , -42.16845  , -46.806065 ],
       [-53.237476 , -59.547493 , -60.84575  , -67.44971  , -69.60702  ],
       [-72.8147   , -77.79634  , -82.681145 , -89.95406  , -96.68995  ]],
      dtype=float32)>

### PEMBAGIAN

In [9]:
tf.divide(x,y)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-0.27670863,  0.34814134,  0.110025  , -0.14183164, -0.0205463 ],
       [ 0.07403754,  0.03691218,  0.06399134,  0.1133367 , -0.00793726],
       [ 0.0578143 , -0.06115074, -0.01634335,  0.01933834,  0.0041263 ],
       [-0.00448067, -0.00927955,  0.00252869, -0.00671202,  0.01961943],
       [ 0.00253837,  0.01523622,  0.00384167, -0.01071981,  0.00319644]],
      dtype=float32)>

### PANGKAT

In [10]:
tf.pow(x,y)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[-2.7670863e-01,  1.1392803e+00,  5.0385658e-02, -9.5081949e-01,
        -7.8593985e-08],
       [ 6.0832995e-01,  3.6267436e-04,  4.0984653e+01,  3.7176028e+09,
        -3.1622396e-19],
       [ 7.1664736e+07, -1.3192539e+13, -7.4322749e-08,  3.5906391e-04,
         3.3110262e-34],
       [-8.0869612e-34, -3.6674136e-16,  0.0000000e+00, -5.5740490e-24,
         1.6598655e+10],
       [ 0.0000000e+00,  2.2899888e+06,  0.0000000e+00, -1.5218512e-02,
         0.0000000e+00]], dtype=float32)>

## 5. Tampilkan nilai maksimum dan minimum dari variable random_tensor.

In [11]:
argmax = tf.constant(random_tensor)
print("Nilai Maksimal random_tensor =",tf.argmax(random_tensor,axis=0))
print("Nilai Minimal random_tensor =",tf.argmin(random_tensor,axis=0))

Nilai Maksimal random_tensor = tf.Tensor([2 4 1 1 3], shape=(5,), dtype=int64)
Nilai Minimal random_tensor = tf.Tensor([0 2 2 0 1], shape=(5,), dtype=int64)


## 6. Tampilkan hasil dari penggabungan variable random_tensor dengan prime_tensor (concatenation)

In [12]:
concat = tf.concat([random_tensor,prime_tensor], axis=0)
concat

<tf.Tensor: shape=(10, 5), dtype=float32, numpy=
array([[-0.27670863,  1.044424  ,  0.550125  , -0.99282146, -0.2260093 ],
       [ 0.962488  ,  0.6275071 ,  1.2158355 ,  2.606744  , -0.23018064],
       [ 1.7922432 , -2.2625775 , -0.6700773 ,  0.83154875,  0.19393615],
       [-0.23747538, -0.5474935 ,  0.15425   , -0.4497052 ,  1.3929794 ],
       [ 0.18530105,  1.2036611 ,  0.31885868, -0.95406336,  0.31005445],
       [ 1.        ,  3.        ,  5.        ,  7.        , 11.        ],
       [13.        , 17.        , 19.        , 23.        , 29.        ],
       [31.        , 37.        , 41.        , 43.        , 47.        ],
       [53.        , 59.        , 61.        , 67.        , 71.        ],
       [73.        , 79.        , 83.        , 89.        , 97.        ]],
      dtype=float32)>

## 7. Tampilkan hasil sorting dari kedua variable di atas (descending)

In [13]:
print("Sorting random_tensor Descending")
print(tf.sort(random_tensor,direction="DESCENDING"))
print("\n")
print("Sorting prime_tensor Descending")
print(tf.sort(prime_tensor,direction="DESCENDING"))

Sorting random_tensor Descending
tf.Tensor(
[[ 1.044424    0.550125   -0.2260093  -0.27670863 -0.99282146]
 [ 2.606744    1.2158355   0.962488    0.6275071  -0.23018064]
 [ 1.7922432   0.83154875  0.19393615 -0.6700773  -2.2625775 ]
 [ 1.3929794   0.15425    -0.23747538 -0.4497052  -0.5474935 ]
 [ 1.2036611   0.31885868  0.31005445  0.18530105 -0.95406336]], shape=(5, 5), dtype=float32)


Sorting prime_tensor Descending
tf.Tensor(
[[11.  7.  5.  3.  1.]
 [29. 23. 19. 17. 13.]
 [47. 43. 41. 37. 31.]
 [71. 67. 61. 59. 53.]
 [97. 89. 83. 79. 73.]], shape=(5, 5), dtype=float32)
